### ISSUE TITLE
MVP Criteria

### ISSUE THREAD

**Issue by ssoonmi** [richierob62/trolle#1]
### Assigning users and teams to boards 
- [x] assigning users to boards should be part of the Boards MVP feature
- [x] Teams should be a bonus MVP

### Cards
- [x] I don't think that cards will take as long to implement as you specified

### Cards Advanced I
- [x] should list out specifically what you want to accomplish

### Board Sharing
- [x] should be another required MVP

### Production README
- [x] should be another required MVP

**Comment by richierob62** [comment]
What exactly is meant by sharing a board? I don't see any "sharing" functionality on the site.  I may have missed it.

**Comment by richierob62** [comment]
Edited
