### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by ssoonmi** [richierob62/trolle#2]
### `users`
- [x] need unique in the `username` details column

### `boards`
- [x] `boards` should belong to a `user` because a `user` can then share the board with other `users` and `teams`

### `visibility`
not sure what this table is for

### `team_boards` and `board_members`
I think you could make the association of attaching teams and users to boards polymorphic. So a board can be shared with a team or a user

### `comments`
not sure why you need to have an index on `[:card_id, :created_at]`

Nice job with the schema!

**Comment by richierob62** [comment]
I'll have to rework  the schema to reflect a user owning a board.  I'd created an "organization" as the owner of a board.  I'll change now that I understand the ownership.

**Comment by richierob62** [comment]
Re: visibility - not sure what this table is for

Visibility on the site can be Private, Team, Organization or Public. These can be hardcoded into the app or kept as a table... Given that the logic of the app would have to be changed to deal with changes to this list, I'll move them to be constants in the app.

**Comment by richierob62** [comment]
Changes made
