### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [richierob62/trolle#3]
### users
- [x] if your app is able to display a list of teams that a user is a part of, then you should have an array of team_ids on a user

### labels
- do labels belong to boards?

Very nice sample state you got there!

**Comment by richierob62** [comment]
Re:  if your app is able to display a list of teams that a user is a part of, then you should have an array of team_ids on a user - I didn't see that anywhere.  I'll add if I do.

Re: do labels belong to boards? - No.  Labels get assigned to cards

**Comment by ssoonmi** [comment]
Aren't labels created for a specific board? And everyone using that board can use any label a user creates?

**Comment by richierob62** [comment]
> Aren't labels created for a specific board? And everyone using that board can use any label a user creates? So shouldn't a label have a `board_id`? Not a `user_id`?

I did  a test.  Yes, they are board specific, not "board owner" specific.  I'll make the change.  Thanks.

**Comment by ssoonmi** [comment]
You changed the labels to be board specific in the schema but not in the sample state

**Comment by richierob62** [comment]
done
